#!/bin/bash

now=`date +%Y%m%dT%H%M%S%z`
out="copy_optics_to_eos_$now.out"
err="copy_optics_to_eos_$now.err"

src="/afs/cern.ch/eng/lhc/optics/"
dst="lxplus:/eos/project/a/abpdata/eng/lhc/optics/"

rsync -vrltgoD --delete --modify-window=2  \
      $src $dst >$out 2>$err &

echo "tail -f $out"
echo "tail -f $err"

